name: pangeo
channels:
  - conda-forge
  - intake
  - default
dependencies:
  - python=3.6
  - pyarrow
  - xarray
  - dask
  - dask-kubernetes
  - distributed
  - gcsfs
  - intake
  - intake-xarray
  - nomkl
  - scipy
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  - nbserverproxy
  - jupyter
  - ipywidgets
  - graphviz
  - nodejs
  - jupyterlab=0.35
  - matplotlib
  - scikit-learn
  - python-graphviz
